// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYnhtgOcePu3PC0ISbWmzGrYczIr8347Q',
    appId: '1:819072192358:web:a9b62d13a9c8101ec7c2a7',
    messagingSenderId: '819072192358',
    projectId: 'netflix2-e5cbe',
    authDomain: 'netflix2-e5cbe.firebaseapp.com',
    storageBucket: 'netflix2-e5cbe.firebasestorage.app',
    measurementId: 'G-368SJCHYFH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAktt5ADX_yWoktAoPQV1MEje7fUYQYpwE',
    appId: '1:819072192358:android:aff016c66b6cdcbac7c2a7',
    messagingSenderId: '819072192358',
    projectId: 'netflix2-e5cbe',
    storageBucket: 'netflix2-e5cbe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVHfUn6Sb2giypBAyfiud4v6Hon2BuCX4',
    appId: '1:819072192358:ios:821dc36095bea905c7c2a7',
    messagingSenderId: '819072192358',
    projectId: 'netflix2-e5cbe',
    storageBucket: 'netflix2-e5cbe.firebasestorage.app',
    iosBundleId: 'com.example.netflixApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVHfUn6Sb2giypBAyfiud4v6Hon2BuCX4',
    appId: '1:819072192358:ios:821dc36095bea905c7c2a7',
    messagingSenderId: '819072192358',
    projectId: 'netflix2-e5cbe',
    storageBucket: 'netflix2-e5cbe.firebasestorage.app',
    iosBundleId: 'com.example.netflixApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYnhtgOcePu3PC0ISbWmzGrYczIr8347Q',
    appId: '1:819072192358:web:5aa356b3f8ea339cc7c2a7',
    messagingSenderId: '819072192358',
    projectId: 'netflix2-e5cbe',
    authDomain: 'netflix2-e5cbe.firebaseapp.com',
    storageBucket: 'netflix2-e5cbe.firebasestorage.app',
    measurementId: 'G-PC8QQTX14T',
  );

}